# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/media/nevy11/myHardDisk/projects/rust/Rust_learning/Actix_server_learning/diesel-learn/rust-diesel-backend/migrations"
